#
# ~/.zshrc
#

# unbreak tramp when zsh is default shell
[[ $TERM == "dumb" ]] && unsetopt zle && PS1='$ ' && return

# zshrc script dir
script_dir="$( cd -P "$( dirname "$(readlink "${(%):-%N}")" )" && pwd )"

# word style
autoload -U select-word-style
select-word-style bash

# history
HISTFILE=~/.zsh_histfile
HISTSIZE=1000
SAVEHIST=1000
setopt appendhistory autocd extendedglob

# use vi mode
bindkey -v

# completions
zstyle :compinstall filename '$(script_dir)/.zshrc'
autoload -Uz compinit
compinit

# keyboard remappings
export XKB_DEFAULT_OPTIONS=ctrl:nocaps

# fix directional keys
bindkey "\e[H"    beginning-of-line
bindkey "\e[1~"   beginning-of-line
bindkey "\e[F"    end-of-line
bindkey "\e[4~"   end-of-line
bindkey "^[[1;5D" backward-word
bindkey "^[Od"    backward-word
bindkey "^[[1;5C" forward-word
bindkey "^[Oc"    forward-word
bindkey "\e[3~"   delete-char
bindkey '^[[3;5~' kill-word
bindkey '^H'      backward-kill-word

# prompt
source ${script_dir}/posh-git-sh/git-prompt.sh
autoload -U colors && colors
precmd() { 
  start_blue="%{$fg[blue]%}"
  start_green="%{$fg[green]%}"
  reset_color="%{$reset_color%}"
  user_host="$start_green%n@%M$reset_color"
  current_path="$start_blue%~$reset_color"
  git_info=$(__posh_git_echo) 
} 
setopt prompt_subst
PROMPT='${user_host}:${current_path}${git_info}> '
export LC_ALL="en_US.UTF-8"

# alias
alias ls='ls --color=auto'
alias sublime='subl3'
alias vscode='code'
alias mkdir="mkdir -p"
alias path='echo $PATH | tr -s ":" "\n"'
alias vim='nvim'
alias history='history 1'
alias ducks='du -cksh * | sort -rh | head -11'
alias ducklings='du -ckhs .[^.]* |sort -rh | head -20'
alias gti='git'
alias reboot='sudo reboot'
alias shutdown='sudo shutdown -h now'

# ROS 
source ${script_dir}/ros/ros_setup.sh

# Other scripts
source ${script_dir}/scripts/knock.sh
source ${script_dir}/scripts/convert_date.sh
source ${script_dir}/scripts/fetch_gravitar.sh
export PATH=$PATH:~/Projects/dotfiles-private/scripts/
export PATH=$PATH:/opt/bin
export PATH=$PATH:~/bin

# make java stuff work nicely w/ wayland
export _JAVA_AWT_WM_NONREPARENTING=1

# Provide owned XDG_RUNTIME_DIR for sway
mkdir -p /tmp/swaytmp
chown -R devin:devin /tmp/swaytmp
export XDG_RUNTIME_DIR=/tmp/swaytmp

# gpg-agent for ssh
export SSH_AUTH_SOCK="/run/user/$(id -u)/gnupg/S.gpg-agent.ssh"
export GPG_TTY=$(tty)
