#
# ~/.zshrc
#

# unbreak tramp when zsh is default shell
[[ $TERM == "dumb" ]] && unsetopt zle && PS1='$ ' && return

# location of this config
zshrc_dir="$( cd -P "$( dirname "$(readlink "${(%):-%N}")" )" && pwd )"

# word style
autoload -U select-word-style
select-word-style bash

# history
HISTFILE=~/.zsh_histfile
HISTSIZE=1000
SAVEHIST=1000
setopt appendhistory autocd extendedglob

# use vi mode
bindkey -v

# completions
zstyle :compinstall filename '$(zshrc_dir)/.zshrc'
autoload -Uz compinit
compinit

# keyboard remappings
export XKB_DEFAULT_OPTIONS=ctrl:nocaps

# fix directional keys
bindkey "\e[H"    beginning-of-line
bindkey "\e[1~"   beginning-of-line
bindkey "\e[F"    end-of-line
bindkey "\e[4~"   end-of-line
bindkey "^[[1;5D" backward-word
bindkey "^[Od"    backward-word
bindkey "^[[1;5C" forward-word
bindkey "^[Oc"    forward-word
bindkey "\e[3~"   delete-char
bindkey '^[[3;5~' kill-word
bindkey '^H'      backward-kill-word

# prompt
source ${zshrc_dir}/posh-git-sh/git-prompt.sh
autoload -U colors && colors
precmd() {
  start_blue="%{$fg[blue]%}"
  start_green="%{$fg[green]%}"
  reset_color="%{$reset_color%}"
  user_host="$start_green%n@%M$reset_color"
  current_path="$start_blue%~$reset_color"
  git_info=$(__posh_git_echo)
}
setopt prompt_subst
PROMPT='${user_host}:${current_path}${git_info}> '
export LC_ALL="en_US.UTF-8"

# alias
alias ls='ls --color=auto'
alias sublime='subl3'
alias vscode='code'
alias mkdir="mkdir -p"
alias path='echo $PATH | tr -s ":" "\n"'
alias vim='nvim'
alias history='history 1'
alias ducks='du -cksh * | sort -rh | head -11'
alias ducklings='du -ckhs .[^.]* |sort -rh | head -20'
alias gti='git'
alias reboot='sudo reboot'
alias shutdown='sudo shutdown -h now'

# ROS
source ${zshrc_dir}/ros/ros_setup.sh

# PATH updates
export PATH=$PATH:${zshrc_dir}/bin
export PATH=$PATH:/opt/bin
export PATH=$PATH:~/.local/bin

# go
export GOPATH=$HOME/.go
export PATH=$PATH:$GOPATH/bin

# make java stuff work nicely w/ wayland
export _JAVA_AWT_WM_NONREPARENTING=1

# gpg-agent for ssh
export SSH_AUTH_SOCK="/run/user/$(id -u)/gnupg/S.gpg-agent.ssh"
export GPG_TTY=$(tty)

# gpg2 crap
function has_gpg2_exec { which gpg2 >/dev/null 2>&1 }
function get_modified_gpg_cmd {
  has_gpg2_exec && echo 'echo "\n********** HEY! THIS IS GPG 1 **********\n" && gpg' || echo 'gpg'
}
export SOPS_GPG_EXEC=$( has_gpg2_exec && which gpg2 || which gpg )
alias gpg="$(get_modified_gpg_cmd)"

