#
# ~/.zshrc
#

# zshrc script dir
script_dir="$( cd -P "$( dirname "$(readlink "${(%):-%N}")" )" && pwd )"

# word style
autoload -U select-word-style
select-word-style bash

# history
HISTFILE=~/.zsh_histfile
HISTSIZE=1000
SAVEHIST=1000
setopt appendhistory autocd extendedglob

# use vi mode
bindkey -v

# completions
zstyle :compinstall filename '$(script_dir)/.zshrc'
autoload -Uz compinit
compinit
bindkey '^H' backward-kill-word

# keyboard remappings
export XKB_DEFAULT_OPTIONS=ctrl:nocaps

# fix directional keys
bindkey "\e[H" beginning-of-line
bindkey "\e[F" end-of-line
bindkey "\e[3~" delete-char
bindkey "^[[1;5D" backward-word
bindkey "^[[1;5C" forward-word
bindkey "^[Od" backward-word
bindkey "^[Oc" forward-word

# prompt
source ${script_dir}/posh-git-sh/git-prompt.sh
precmd() { git_info=$(__posh_git_echo) } 
setopt prompt_subst
PROMPT='%/${git_info}> '
export LC_ALL="en_US.UTF-8"

# alias
alias ls='ls --color=auto'
alias sublime='subl3'
alias vscode='code'
alias mkdir="mkdir -p"
alias path='echo $PATH | tr -s ":" "\n"'
alias vim='nvim'
alias history='history 1'
alias ducks='du -cksh * | sort -rh | head -11'
alias ducklings='du -ckhs .[^.]* |sort -rh | head -20'
alias gti='git'

# ROS 
source ${script_dir}/ros/ros_setup.sh

# Other scripts
source ${script_dir}/scripts/knock.sh
source ${script_dir}/scripts/convert_date.sh
export PATH=~/Projects/dotfiles-private/scripts/:$PATH

# make java stuff work nicely w/ wayland
export _JAVA_AWT_WM_NONREPARENTING=1
