#!/bin/bash
#
# ~/.bashrc
#

# location of this config
bashrc_dir=$(cd "$(dirname "$BASH_SOURCE")"; cd -P "$(dirname "$(readlink "$BASH_SOURCE" || echo .)")"; pwd)

# prompt
source "$bashrc_dir/prompt/bash_prompt"

# tab completion
bind 'set show-all-if-ambiguous on'

# xdg definitions
export XDG_CONFIG_HOME="$HOME"/.config
export XDG_CACHE_HOME="$HOME"/.cache
export XDG_DATA_HOME="$HOME"/.local/share
export XDG_STATE_HOME="$HOME"/.local/state
export XDG_RUNTIME_DIR=/run/user/$(id -u)

# history
mkdir -p "$XDG_STATE_HOME"/bash
export HISTFILE="$XDG_STATE_HOME"/bash/history
export HISTSIZE=10000
export HISTFILESIZE=10000

# alias
alias ls='ls --color=auto'
alias mkdir="mkdir -p"
alias path='echo $PATH | tr -s ":" "\n"'
alias vim='nvim'
alias history='history 1'
alias tophistory='history | cut -c 8- | sort | uniq -c | sort -rn | head -n 10'
alias ducks='du -cksh $(ls -A) | sort -rh | head -n 10'
alias gti='git'
alias contributers='git log --format='%aN' | sort | uniq -c | sort -rn | head -n 10'

# PATH updates

pathappend() {
  if [ -d "$1" ] && [[ ":$PATH:" != *":$1:"* ]]; then
    PATH="${PATH:+"$PATH:"}$1"
  fi
}
    
pathprepend() {
  if [ -d "$1" ] && [[ ":$PATH:" != *":$1:"* ]]; then
    PATH="$1${PATH:+":$PATH"}"
  fi
}

pathprepend $HOME/.local/bin
pathappend $bashrc_dir/script
pathappend /opt/bin

# go
export GOPATH=$XDG_DATA_HOME/.go
pathappend $GOPATH/bin

# gpg-agent for ssh
export SSH_AUTH_SOCK="/run/user/$(id -u)/gnupg/S.gpg-agent.ssh"
export GPG_TTY=$(tty)

# gpg2 crap
function has_gpg2_exec {
  which gpg2 >/dev/null 2>&1
}
function get_modified_gpg_cmd {
  has_gpg2_exec && echo 'echo "\n********** HEY! THIS IS GPG 1 **********\n" && gpg' || echo 'gpg'
}
export SOPS_GPG_EXEC=$( has_gpg2_exec && which gpg2 || which gpg )
alias gpg="$(get_modified_gpg_cmd)"

# wayland odds and ends
if test -f ${XDG_CONFIG_HOME}/bash/env-wayland; then
    source ${XDG_CONFIG_HOME}/bash/env-wayland
fi

# apps that don't XDG nicely
if test -f ${XDG_CONFIG_HOME}/bash/env-xdg; then
    source ${XDG_CONFIG_HOME}/bash/env-xdg
fi

# flatpak aliases
if test -f ${XDG_CONFIG_HOME}/bash/env-flatpak; then
    source ${XDG_CONFIG_HOME}/bash/env-flatpak
fi

# opam
[[ ! -r ${XDG_DATA_HOME}/opam/opam-init/init.zsh ]] || source ${XDG_DATA_HOME}/opam/opam-init/init.zsh  > /dev/null 2> /dev/null

